title: Jekyll x GitHub 101
author: grimmer-std
email: example@example.com
description: > # this means to ignore newlines until "baseurl:"
  First on teh interwebz.
# social links
twitter_username: Grimmer-std
github_username:  grimmer-std
theme: minima
show_excerpts: true # set to false to remove excerpts on the homepage
